/**
 * Core install-pipeline types. Mirrors the ECC adapter pattern (see
 * `docs/research/phase-3-ecc-install-patterns.md`): a `TargetAdapter` turns a
 * resolved profile into an `InstallPlan` (a list of file operations, NO writes);
 * the installer materializes the plan.
 *
 * Phase 3.3 ships these types + a stub adapter + the plan/apply machinery. Real
 * target adapters (Hermes/CC/Codex) arrive in 3.4–3.6.
 */
import type { AgentTarget, Profile, McpServer, Resource } from '@harness-nexus/core';

/** Where an adapter installs: a user home dir (`~/.xxx`) or a project root. */
export type AdapterKind = 'home' | 'project';

/** A single filesystem operation the installer can materialize. */
export type Operation =
  | {
      kind: 'copy-file';
      /** Absolute source path (a resolved profile artifact on disk). */
      sourcePath: string;
      /** Absolute destination path in the target tool's layout. */
      destinationPath: string;
    }
  | {
      kind: 'write-file';
      /** Inline content to write (generated by the adapter). */
      content: string;
      destinationPath: string;
    }
  | {
      kind: 'merge-json';
      /** The JSON value to deep-merge into the destination file. */
      mergePayload: unknown;
      destinationPath: string;
    };

/** The output of planning — a serializable, dry-runnable description of an install. */
export interface InstallPlan {
  adapter: { id: string; target: AgentTarget; kind: AdapterKind };
  /** Root dir the adapter writes into (e.g. ~/.hermes, ~/.codex). */
  targetRoot: string;
  /** Where the install-state ledger is written. */
  installStatePath: string;
  operations: Operation[];
  /** True if any operation carries a decrypted direct-mode credential. */
  sensitive: boolean;
}

/** Input passed to an adapter's resolve/plan/validate methods. */
export interface ResolveInput {
  /** Override the adapter's default home/project root. */
  outDir?: string;
  /** The OS home dir (defaults to os.homedir()). */
  homeDir?: string;
}

/** A non-fatal adapter validation finding. severity 'error' blocks planning. */
export interface ValidationIssue {
  severity: 'error' | 'warning';
  code: string;
  message: string;
}

/**
 * A profile entry resolved to its concrete artifact. MCP entries resolve to a
 * McpServer row; other kinds resolve to a Resource. Used by adapters to emit
 * target-native files.
 */
export type ResolvedArtifact =
  | { entryId: string; kind: 'mcp'; mcpServer: McpServer }
  | {
      entryId: string;
      kind: Exclude<Profile['entries'][number]['kind'], 'mcp'>;
      resource: Resource;
    };

/** A profile plus every entry's artifact, fetched from the server. */
export interface ResolvedProfile {
  profile: Profile;
  artifacts: ResolvedArtifact[];
}

/**
 * A target adapter — one per Agent tool. Produced by `createTargetAdapter`.
 * The contract: turn a resolved profile into an install plan, no writes.
 */
export interface TargetAdapter {
  readonly id: string;
  readonly target: AgentTarget;
  readonly kind: AdapterKind;
  /** Resolve the root dir files land under (honors `outDir` override). */
  resolveRoot(input: ResolveInput): string;
  /** Plan file operations for a resolved profile. Does NOT write. */
  planOperations(resolved: ResolvedProfile, input: ResolveInput): InstallPlan;
  /** Gate before planning; 'error' severity blocks. */
  validate(input: ResolveInput): ValidationIssue[];
}
