/**
 * Hermes target adapter (Phase 3.4 — first real adapter, priority 1).
 *
 * Hermes is a Python agent with a YAML-native config model. An install emits
 * THREE things:
 *  A. a Python **plugin bundle** at `~/.hermes/plugins/<profile>/` (skills).
 *  B. MCP servers merged (YAML add-only) into `~/.hermes/config.yaml` `mcp_servers:`.
 *  C. rules as `AGENTS.md` at the install root (Hermes auto-loads it).
 *
 * sub_agents and hooks are SKIPPED (Hermes has no file format for either —
 * sub_agents are a runtime `delegate_task` tool; hooks are Python callbacks, not
 * declarative hooks.json). Both surface as skipped warnings.
 *
 * Ground-truth format: `docs/research/phase-3-ecc-install-patterns.md` +
 * verified against `~/.hermes/hermes-agent/hermes_cli/{plugins,mcp_config}.py`.
 *
 * Uninstall/upgrade reliability: the config.yaml merge is a single `write-file`
 * operation recorded in the install-state ledger, so a future `hnx uninstall`
 * can roll it back. Hermes's own `hermes plugins remove` has a config-cleanup
 * gap (leaves stale `plugins.enabled`), so we rely on our ledger, not Hermes.
 */
import fs from 'node:fs';
import path from 'node:path';
import yaml from 'js-yaml';
import { createTargetAdapter } from '../adapter-factory.js';
import { hnxExecutablePath } from '../../config.js';
import type {
  InstallPlan,
  Operation,
  ResolvedArtifact,
  ResolvedProfile,
  ResolveInput,
  TargetAdapter,
} from '../types.js';

/** The install-state ledger filename inside the Hermes home. */
const INSTALL_STATE_FILENAME = 'harness-nexus-install-state.json';

/** A resource kind Hermes cannot emit as a file artifact. */
const SKIPPED_KINDS = new Set(['sub_agent', 'hook', 'command']);

/** A sanitizer for profile/plugin names used as a directory + Python module name. */
function slugify(name: string): string {
  return (
    name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 64) || 'harness-nexus-profile'
  );
}

/** Build the `plugin.yaml` content (Hermes PluginManifest schema). */
function pluginYaml(profile: ResolvedProfile['profile']): string {
  const slug = slugify(profile.name);
  const manifest: Record<string, unknown> = {
    name: slug,
    version: profile.version || '1.0.0',
    description: profile.description ?? `Harness Nexus profile '${profile.name}'.`,
    author: 'Harness Nexus',
    kind: 'standalone',
  };
  return yaml.dump(manifest, { lineWidth: 100 });
}

/**
 * Build the `__init__.py` exposing `register(ctx)`, which registers each skill
 * via `ctx.register_skill(name, path, description)`. Plugin skills resolve as
 * `<plugin>:<skill>` in Hermes and are opt-in (not in the system-prompt index).
 */
function pluginInitPy(
  profile: ResolvedProfile['profile'],
  skills: { name: string; description: string }[],
): string {
  const slug = slugify(profile.name);
  const lines = [
    '"""Harness Nexus profile plugin (auto-generated by `hnx install`)."""',
    'from pathlib import Path',
    '',
    '',
    'def register(ctx):',
    '    _root = Path(__file__).parent',
  ];
  for (const s of skills) {
    const pyName = JSON.stringify(s.name);
    const pyPath = `str(_root / "skills" / ${pyName})`;
    const pyDesc = JSON.stringify(s.description);
    lines.push(`    ctx.register_skill(${pyName}, ${pyPath}, ${pyDesc})`);
  }
  lines.push('');
  // Suppress the unused-import lint for `slug` if no skills (keeps it valid Python).
  void slug;
  return lines.join('\n');
}

/** Extract skill content from a Resource's source (inline / inline-bundle). */
function skillFiles(
  artifact: ResolvedArtifact,
): { relativePath: string; content: string; description: string }[] {
  if (artifact.kind === 'mcp') return [];
  const resource = artifact.resource;
  const src = resource.source;
  const description = resource.description ?? '';
  if (src.type === 'inline') {
    return [{ relativePath: 'SKILL.md', content: src.content, description }];
  }
  if (src.type === 'inline-bundle') {
    return Object.entries(src.files).map(([rel, content]) => ({
      relativePath: rel,
      content,
      description,
    }));
  }
  // External sources (git/tarball/local/plugin) are not fetchable by the CLI at
  // install time; only inline content can be emitted. The resolver would need a
  // content-fetch step — out of scope for 3.4. Emit nothing + the caller warns.
  return [];
}

/** The Hermes config.yaml path under the install root. */
function configYamlPath(root: string): string {
  return path.join(root, 'config.yaml');
}

/**
 * Plan the MCP merge into config.yaml. Reads the existing config (if any),
 * adds/overwrites the profile's stdio shim entry under `mcp_servers:`,
 * preserves all other user content, and returns a single `write-file` op with
 * the full merged YAML. The ledger records this op so uninstall can roll it
 * back.
 *
 * Phase 8 C2: every profile collapses into ONE stdio shim entry —
 * `hnx mcp serve --profile <id> --server <base>` — regardless of dial sites.
 * The shim dials client-dialed upstreams itself and reaches server-dialed
 * ones through the platform outlet, so no credential ever lands in config.yaml
 * (the pre-C2 direct-mode inlining and the `${HN_PAT_*}` env placeholder are
 * gone).
 */
function planMcpMerge(resolved: ResolvedProfile, root: string, serverBase: string): Operation {
  const cfgPath = configYamlPath(root);
  let config: Record<string, unknown> = {};
  if (fs.existsSync(cfgPath)) {
    try {
      const parsed = yaml.load(fs.readFileSync(cfgPath, 'utf8'));
      if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) {
        config = parsed as Record<string, unknown>;
      }
    } catch {
      // Unparseable config: leave config empty and overwrite (best-effort).
    }
  }

  const mcpServers = (config['mcp_servers'] as Record<string, unknown> | undefined) ?? {};
  const slug = slugify(resolved.profile.name);
  const mcpCount = resolved.artifacts.filter((a) => a.kind === 'mcp').length;
  if (mcpCount > 0) {
    mcpServers[`harness-nexus-${slug}`] = {
      command: hnxExecutablePath(),
      args: ['mcp', 'serve', '--profile', resolved.profile.id, '--server', serverBase],
    };
  }

  config['mcp_servers'] = mcpServers;
  const dumped = yaml.dump(config, { lineWidth: 100 });
  return { kind: 'write-file', content: dumped, destinationPath: cfgPath };
}

/**
 * The Hermes adapter. Overrides `planOperations` to emit the plugin bundle,
 * the config.yaml MCP merge, and the AGENTS.md rule file.
 */
export const hermesAdapter: TargetAdapter = createTargetAdapter({
  id: 'hermes-home',
  target: 'hermes',
  kind: 'home',
  rootSegments: ['.hermes'],

  planOperations(
    resolved: ResolvedProfile,
    input: ResolveInput,
    adapter: TargetAdapter,
  ): InstallPlan {
    const root = adapter.resolveRoot(input);
    const slug = slugify(resolved.profile.name);
    const pluginDir = path.join(root, 'plugins', slug);
    const operations: Operation[] = [];
    const skipped: string[] = [];

    // ---- A. Plugin bundle (skills only) ----
    const skillArtifacts = resolved.artifacts.filter((a) => a.kind === 'skill');
    const skillMeta: { name: string; description: string }[] = [];

    if (skillArtifacts.length > 0) {
      // plugin.yaml
      operations.push({
        kind: 'write-file',
        content: pluginYaml(resolved.profile),
        destinationPath: path.join(pluginDir, 'plugin.yaml'),
      });
      // skills + collect meta for __init__.py
      for (const a of skillArtifacts) {
        if (a.kind === 'mcp') continue;
        const files = skillFiles(a);
        if (files.length === 0) {
          skipped.push(`skill:${a.resource.key} (non-inline source not fetchable by CLI)`);
          continue;
        }
        const skillDir = path.join(pluginDir, 'skills', a.resource.name);
        for (const f of files) {
          operations.push({
            kind: 'write-file',
            content: f.content,
            destinationPath: path.join(skillDir, f.relativePath),
          });
        }
        skillMeta.push({ name: a.resource.name, description: a.resource.description ?? '' });
      }
      // __init__.py
      operations.push({
        kind: 'write-file',
        content: pluginInitPy(resolved.profile, skillMeta),
        destinationPath: path.join(pluginDir, '__init__.py'),
      });
    }

    // ---- B. MCP merge into config.yaml ----
    // The shim entry needs the server base URL. The adapter doesn't receive
    // the resolver's server directly, so the CLI sets HN_SERVER before
    // planning (see runInstall); a sensible fallback covers direct
    // planInstall() use in tests.
    const serverBase = process.env.HN_SERVER ?? 'https://harness-nexus.example.com';
    const hasMcp = resolved.artifacts.some((a) => a.kind === 'mcp');
    if (hasMcp) {
      operations.push(planMcpMerge(resolved, root, serverBase));
    }

    // ---- C. Rules → AGENTS.md (auto-loaded by Hermes) ----
    const ruleArtifacts = resolved.artifacts.filter((a) => a.kind === 'rule');
    if (ruleArtifacts.length > 0) {
      // Concatenate rule contents into one AGENTS.md (Hermes loads a single file).
      const body = ruleArtifacts
        .map((a) => {
          if (a.kind === 'mcp') return '';
          const src = a.resource.source;
          return src.type === 'inline'
            ? src.content
            : `# ${a.resource.name}\n(non-inline source skipped)`;
        })
        .filter(Boolean)
        .join('\n\n---\n\n');
      if (body) {
        operations.push({
          kind: 'write-file',
          content: body,
          destinationPath: path.join(root, 'AGENTS.md'),
        });
      }
    }

    // ---- skipped kinds ----
    for (const a of resolved.artifacts) {
      if (SKIPPED_KINDS.has(a.kind)) {
        if (a.kind === 'mcp') continue;
        const reason =
          a.kind === 'sub_agent'
            ? 'Hermes has no file-based sub-agent format (runtime delegate_task only)'
            : a.kind === 'hook'
              ? 'Hermes hooks are Python callbacks, not declarative hooks.json'
              : 'commands are not emitted for Hermes in 3.4';
        skipped.push(`${a.kind}:${a.resource.key} (${reason})`);
      }
    }

    // Stash diagnostics on the plan via a non-enumerable side channel the CLI
    // can read (kept simple: module-level last-warnings for 3.4).
    lastPlanWarnings = {
      skipped,
      needsHnx: hasMcp,
      pluginSlug: slug,
      needsPluginEnable: skillArtifacts.length > 0,
    };

    return {
      adapter: { id: adapter.id, target: adapter.target, kind: adapter.kind },
      targetRoot: root,
      installStatePath: path.join(root, INSTALL_STATE_FILENAME),
      operations,
      sensitive: false,
    };
  },
});

/** Warnings from the most recent hermes planInstall (read by the CLI for output). */
export interface HermesPlanWarnings {
  skipped: string[];
  /** True when the plan carries a `hnx mcp serve` shim entry. */
  needsHnx: boolean;
  pluginSlug: string;
  needsPluginEnable: boolean;
}
let lastPlanWarnings: HermesPlanWarnings = {
  skipped: [],
  needsHnx: false,
  pluginSlug: '',
  needsPluginEnable: false,
};
export function getHermesPlanWarnings(): HermesPlanWarnings {
  return lastPlanWarnings;
}
